name: Detect Objects on Camera
icon: 📽️
description: This example showcases object detection within a live feed from a USB camera.

bricks:
  - arduino:video_object_detection: {
    variables: {
      EI_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/ei-models/model.eim
    }
  }
  - arduino:web_ui