name: Face Inference Test
description: "Perform inference on a static image"
icon: ⚛
version: "1.0.0"

# Define any exposed ports
ports: []

# Define bricks if using pre-built components
bricks: []